### ISSUE TITLE
Por que um mirror melhor?

### ISSUE THREAD

**Issue by chiefGui** [nodebr/npmjs.com.br#1]
Achei curioso o nome **npmjs.com.br** e gostaria de saber: por que um mirror melhor? O propósito é fazermos downloads mais rápidos?

**Comment by alanhoff** [comment]
Latência menor, download mais rápido, instalação de pacotes mais rápida e se o npmjs.org cair, ainda vamos ter o cache por aqui. Isso que não vou entrar no assunto sobre desafogar o npmjs.org, etc...
